//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccidentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Force { get; set; }
        public string Flame { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    
        public virtual User User { get; set; }
    }
}
