//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccidentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string uMobile { get; set; }
        public string uEmail { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string rMobile { get; set; }
        public string rEmail { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
        public virtual GSM GSM { get; set; }
    }
}
